# Generated by Django 3.2.13 on 2022-12-12 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('content1', models.TextField()),
                ('img1', models.CharField(max_length=100)),
                ('content2', models.TextField(blank=True)),
                ('img2', models.CharField(blank=True, max_length=100)),
                ('content3', models.TextField(blank=True)),
                ('img3', models.CharField(blank=True, max_length=100)),
                ('content4', models.TextField(blank=True)),
                ('img4', models.CharField(blank=True, max_length=100)),
                ('content5', models.TextField(blank=True)),
                ('img5', models.CharField(blank=True, max_length=100)),
                ('content6', models.TextField(blank=True)),
                ('img6', models.CharField(blank=True, max_length=100)),
                ('content7', models.TextField(blank=True)),
                ('img7', models.CharField(blank=True, max_length=100)),
                ('content8', models.TextField(blank=True)),
                ('img8', models.CharField(blank=True, max_length=100)),
                ('content9', models.TextField(blank=True)),
                ('img9', models.CharField(blank=True, max_length=100)),
                ('content10', models.TextField(blank=True)),
                ('img10', models.CharField(blank=True, max_length=100)),
                ('ingredient', models.ManyToManyField(related_name='menu_ingredients', to='foods.Ingredient')),
                ('like_users', models.ManyToManyField(related_name='like_recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=100)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foods.recipe')),
            ],
        ),
    ]
