# Generated by Django 3.2.13 on 2022-12-14 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='menuname',
        ),
        migrations.AddField(
            model_name='history',
            name='menuname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Mymenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.history')),
            ],
        ),
    ]
